modLoader="javafml"
loaderVersion="[35,)"
license="MIT License"

[[mods]]
modId="imstuff"
version="1.0.0"
displayName="imstuff"
credits="very good mod"
displayURL="https://nierot.com"
authors="Nierot"
description='''
Random things
'''

[[dependencies.imstuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




